#!/bin/bash
set -e
echo "Creating database, user and assignment for: $METABASE_DBUSER onto $METABASE_DBNAME"
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE USER $METABASE_DBUSER WITH
    LOGIN
    NOSUPERUSER
    NOCREATEDB
    NOCREATEROLE
    NOINHERIT
    NOREPLICATION
    PASSWORD '$METABASE_DBPASSWORD';
    CREATE DATABASE $METABASE_DBNAME OWNER $METABASE_DBUSER;
    GRANT ALL PRIVILEGES ON DATABASE $METABASE_DBNAME TO $METABASE_DBUSER;
EOSQL